name: Test Parkalot Bot

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run script in test mode
        run: python parkalot_bot.py --test
