import datetime
import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

print("Starting Parkalot Booking Bot...")

# --- Credentials ---
PARKALOT_EMAIL = os.getenv("PARKALOT_EMAIL")
PARKALOT_PASSWORD = os.getenv("PARKALOT_PASSWORD")
print(f"Loaded email: {PARKALOT_EMAIL is not None}, password: {PARKALOT_PASSWORD is not None}")

# --- Calculate Target Date ---
target_date = datetime.date.today() + datetime.timedelta(days=14)
target_day = target_date.strftime("%A")
target_day_num = target_date.strftime("%-d")
target_month = target_date.strftime("%B")
target_label = f"{target_day} {target_day_num} {target_month}"
print(f"Booking attempt for {target_label}...")

# --- Selenium Setup ---
options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

try:
    driver = webdriver.Chrome(options=options)
    print("Chrome started successfully...")
except Exception as e:
    print(f"Error starting Chrome: {e}")
    exit(1)
