import sys
import datetime

if '--test' in sys.argv:
    # Find the next Sunday
    today = datetime.date.today()
    days_ahead = 6 - today.weekday()  # Sunday = 6
    if days_ahead <= 0:
        days_ahead += 7
    target_date = today + datetime.timedelta(days=days_ahead)
else:
    target_date = datetime.date.today() + datetime.timedelta(days=14)

target_label = target_date.strftime("%A %d %B")
print(f"Booking attempt for {target_label}...")
